Support setting a custom deletewritemode.strategy
mongodb/mongo-kafka pull request #108
Opened 2022-07-14 12:53 UTC by ArneKlein

Hi,

we currently have the scenario where we have to create multi version of the same document based on a key in the value and delete all versions based on the key once we receive a tombstone event.

To support this scenario, it would be great to enable setting a custom "deletewritemodel.strategy" just as we currently can for the normal writemodel.strategy

2022-09-14 08:39 UTC, rozza requested changes
Apologies for the delay in reviewing. 

I've added a couple of minor nits for being included into master. 
I would like to see some tests added to test the new logic

2022-09-14 08:39 UTC, rozza commented on src/main/java/com/mongodb/kafka/connect/sink/MongoSinkTopicConfig.java
> +  public static final String DELETEWRITEMODEL_STRATEGY_CONFIG = "deletewritemodel.strategy";
Rename to `DELETE_WRITEMODEL_STRATEGY_CONFIG` and config to: `delete.writemodel.strategy`

2022-09-14 08:39 UTC, rozza commented on src/main/java/com/mongodb/kafka/connect/sink/MongoSinkTopicConfig.java
>    public WriteModelStrategy getWriteModelStrategy() {
Seems strange to have two methods with the same name. But having different effects (one caching). I'd be tempted to refactor / rename eg: `getWriteModelStrategyFromConfig`

2022-09-21 13:42 UTC, ArneKlein commented
> Apologies for the delay in reviewing.
> 
> I've added a couple of minor nits for being included into master. I would like to see some tests added to test the new logic

Thank you for the review, I added basically the same tests as for getWriteModelStrategy(). Please let me know if this is sufficient

2022-10-04 13:38 UTC, rozza approved these changes

2022-10-04 13:38 UTC, rozza commented
LGTM

2023-03-30 16:43 UTC, ArneKlein commented
Any chance that this can get merged?

2023-04-06 23:20 UTC, jyemin commented
Note: the latest patch doesn't compile:

```
com/mongodb/kafka/connect/sink/MongoSinkConfigTest.java:812: error: incompatible types: Optional<WriteModelStrategy> cannot be converted to WriteModelStrategy
               cfg.getMongoSinkTopicConfig(TEST_TOPIC).getDeleteWriteModelStrategy();
```

2023-05-01 13:58 UTC, merged