Kafka-348 SSL Support Added
mongodb/mongo-kafka pull request #131
Opened 2023-02-02 17:53 UTC by bdesert

Adding SSL Support on connector level.

[KAFKA-348](https://jira.mongodb.org/browse/KAFKA-348)

Current state:
In order to support SSL, four ssl parameters should be defined on a system level.
It is described [in documentation](https://www.mongodb.com/docs/kafka-connector/current/security-and-authentication/tls-and-x509/#add-credentials-to-the-connector).

In managed environments, like MSK Connect, this is not possible as a user doesn't have an access to the OS.

New Feature:
I'm introducing four new connector properties:
```properties
connection.ssl.truststore=<your path to truststore>
connection.ssl.truststorePassword=<your truststore password>
connection.ssl.keystore=<your path to keystore>
connection.ssl.keystorePassword=<your keystore password>
```

Note, current implementations fully mimicking suggested approach for setting up default SSLConect using Java System Properties.

2023-02-02 17:55 UTC, bdesert commented
This is initial PR to review the approach and let me know if this is OK or not.

I continue working on non-functional part: unit tests will be added to this PR soon.

2023-02-07 07:05 UTC, bdesert commented
@rozza , would appreciate your input on the following:

currently I see that Sink/Source connectors' `validate` method is covered only in integrationTest in ConnectorValidationIntegrationTest. These tests are for Sink connector and don't cover Source.

I'm planning to create new test Class also in integrationTest task, to cover only SSL parameters.

Please let me know if this will work, or if you have any recommendations.

2023-02-07 11:22 UTC, rozza requested changes
Hi @bdesert, 

Thanks for the PR!

Regarding testing, I added the integration tests due to the custom connection and auth permissions validation. I didn't add any tests for using the default Kafka configurations.

I think in this instance adding a unit test ensuring the properties are added as expected would work.  I'll ensure that the CI gets updated to handle the integration tests.

For the approach I see that this mimics using `KAFKA_OPTS` as passed in via [kafka-run-class.sh](https://github.com/apache/kafka/blob/3.4.0/bin/kafka-run-class.sh#L343-L347) so the approach should be good.

An alternative approach if ever required would be to create a custom SSLContext - similar to how [SSLUtils](https://github.com/apache/kafka/blob/3.4.0/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest/util/SSLUtils.java) configures jetty's `SslContextFactory`.  Given we've had no issues reported using `KAFKA_OPTS` it might not be required.

Any thoughts here @jyemin?

2023-02-08 14:05 UTC, jyemin commented
* Could there be other connectors deployed in the same JVM process that would not want to use these system properties?
* Does Kafka itself make TLS connections that would not want to use these system properties?

If either of these are true, then it seems unsafe to update global JVM state like this, and configuring SslContext on the MongoClientSettings would be a more conservative approach to solving the problem.

2023-02-08 15:38 UTC, bdesert commented
@jyemin , thanks for your comment.
As mentioned in the description, in this PR I'm implementing [suggested/recommended](https://www.mongodb.com/docs/kafka-connector/current/security-and-authentication/tls-and-x509/#add-credentials-to-the-connector) way to set up SSL configuration in programmatic way.

I do agree that in multi-tenant Kafka Connect environment, other connectors may use their own certificates, hence new version (with requires much higher effort to implement) will be developed and submitted for review, and will implement SSLContext that used for mongodb client only.

As for the Kafka, I don't see any issues with Kafka connectivity from the worker side. the mongo side certificates should be added to the existing and valid trust store that would trust Kafka brokers.

And again, if this is wrong approach, we need to review the documentation for SSL-based connectivity described by the link above.

It could be that I'm missing something, so I'm open for discussion. let me know please.

2023-02-09 04:04 UTC, jyemin commented
My opinion is that it's too risky to release a connector that sets these global system properties, and I'd like to go for SSLContext approach right off the bat.  I've always wondered though how one programmatically initialized an SSLContext in this type of scenario, so I tried to work it out.  I think it's as simple as this:

```
        String trustStorePath = ...
        char[] trustStorePassword = ...

        String keyStorePath = ...
        char[] keyStorePassword = ...

        SSLContext sslContext = SSLContext.getInstance("TLS");
        try (InputStream keyStoreInputStream = Files.newInputStream(Paths.get(keyStorePath));
               InputStream trustStoreInputStream = Files.newInputStream(Paths.get(trustStorePath))) {
            
            KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
            keyStore.load(keyStoreInputStream, keyStorePassword);

            KeyManagerFactory keyManagerFactory =
                     KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(keyStore, keyStorePassword);
            KeyManager[] keyManagers = keyManagerFactory.getKeyManagers();

            KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
            trustStore.load(trustStoreInputStream, trustStorePassword);

            TrustManagerFactory trustManagerFactory = 
                    TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            trustManagerFactory.init(trustStore);
            TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();

            sslContext.init(keyManagers, trustManagers, null);
        }
```

Once we have the SSLContext configured, it's just a matter of settings in on the MongoClientSettings in the source and sink tasks.  What do you think?

2023-02-13 14:02 UTC, jyemin reviewed
Comment added above.  Waiting for feedback.

2023-02-15 04:39 UTC, bdesert commented on src/main/java/com/mongodb/kafka/connect/util/SslConfigs.java
> +  public static void setupSsl(final AbstractConfig connectorConfig) {
This is done. please review and let me know. I the meantime, I'll respond to the @jyemin below as well.

2023-02-15 05:35 UTC, bdesert commented
@jyemin , I agree - that is the way to implement SSLContext. I wanted to reduce the regression risks (read as "I'm lazy"). But started digging into the client code, and found a way to implement it relatively easy. Working on these changes. Still wanted to add unit test to initial version to keep in history in case we decide to go with simple version. 

Alternatively, I can create new PR, so we have both versions. would appreciate your opinion on this.

2023-02-15 13:39 UTC, jyemin commented
Feel free to open a new PR.  Thanks.

2023-02-27 17:09 UTC, jyemin commented
Superseded by #132

2023-02-27 17:09 UTC, closed without merging