Errant Record Reporter
mongodb/mongo-kafka pull request #57
Opened 2021-02-19 11:52 UTC by rozza

This PR has two commits: 

* The first updates the Kafka version to one that supports the errant record reporter and updates some of the testing framework
* The second adds errant record reporting if available. This caused some extra refactoring to centralize the error reporting. Now the MongoSinkRecordProcessor handles errors and reporting of them.

2021-02-19 11:54 UTC, rozza commented on src/main/java/com/mongodb/kafka/connect/sink/cdc/debezium/DebeziumCdcHandler.java
> -import java.util.Optional;
The responsibility of respecting errors tolerance and error reporting is now all in one place.

2021-02-19 11:56 UTC, rozza commented on src/main/java/com/mongodb/kafka/connect/sink/MongoSinkTask.java
> +      try {
This logic is per: https://kafka.apache.org/26/javadoc/org/apache/kafka/connect/sink/SinkTaskContext.html#errantRecordReporter--

2021-03-01 06:02 UTC, stIncMale requested changes

2021-03-01 09:56 UTC, rozza commented on build.gradle.kts
> +    mavenCentral()
I had an issue resolving artifacts from Maven Central, due to a temporary issue. As these are confluent packages made sense to resolve there first.

2021-03-01 09:57 UTC, rozza commented on src/integrationTest/java/com/mongodb/kafka/connect/embedded/EmbeddedKafka.java
> +          broker.stopAsync();
Not for the test environment.

2021-03-01 10:20 UTC, rozza commented on src/main/java/com/mongodb/kafka/connect/sink/MongoProcessedSinkRecordData.java
> -    if (writeModel == null) {
Thats correct and this is checked.  The reason for this is there are certain scenarios where a message from the topic doesn't require a write to the database. (The Debezium CDC tombstone event is one, or a Change stream invalidate event could be another).

2021-03-01 10:20 UTC, rozza commented on src/integrationTest/java/com/mongodb/kafka/connect/embedded/EmbeddedKafka.java
> +    if (topicArray.length > 0) {
Done

2021-03-01 10:20 UTC, rozza commented on src/main/java/com/mongodb/kafka/connect/sink/MongoSinkTopicConfig.java
> +  public Optional<CdcHandler> getCdcHandler() {
Reverted - thanks.

2021-03-01 10:20 UTC, rozza commented on src/main/java/com/mongodb/kafka/connect/sink/writemodel/strategy/WriteModelStrategyHelper.java
> +      return Optional.of(createKeyDeleteOneModel(config, document));
Done.

2021-03-01 10:20 UTC, rozza commented on build.gradle.kts
> +    mavenCentral()
I switched due to mavenCentral having an issue.  As there are confluent packages we used I switched the resolution order.

2021-03-01 10:35 UTC, rozza commented on src/integrationTest/java/com/mongodb/kafka/connect/embedded/EmbeddedKafka.java
> +          broker.stopAsync();
It hasn't been an issue but added the check as well.

2021-03-02 06:53 UTC, stIncMale commented on src/main/java/com/mongodb/kafka/connect/sink/MongoProcessedSinkRecordData.java
> -    if (writeModel == null) {
> Thats correct and this is checked. 

I did not find where we check for `null` elements and filter them out. I see the following (I apologize if I am missing something, please correct me):
- The `writeModels` list is passed to `com.mongodb.client.MongoCollection.bulkWrite(List<? extends WriteModel<? extends TDocument>> requests, BulkWriteOptions options)` as `requests`.
- Eventually `com.mongodb.internal.operation.Operations.bulkWrite(List<? extends WriteModel<? extends TDocument>> requests, BulkWriteOptions options)` is called.
- If the `requests` list contains `null`, `IllegalArgumentException("requests can not contain a null value")` is thrown.

2021-03-02 10:26 UTC, rozza commented on src/main/java/com/mongodb/kafka/connect/sink/MongoProcessedSinkRecordData.java
> -    if (writeModel == null) {
So the MongoProcessedSinkRecordData objects are grouped in order by topic and namespace. That is where the null checks are done.  See: https://github.com/mongodb/mongo-kafka/blob/bae87bf343107bee7ccf4476dd8844ddf6d02989/src/main/java/com/mongodb/kafka/connect/sink/MongoSinkRecordProcessor.java#L51

2021-03-02 15:49 UTC, stIncMale commented on src/main/java/com/mongodb/kafka/connect/sink/MongoProcessedSinkRecordData.java
> -    if (writeModel == null) {
Thanks 🙇 , I see it now: `null` write models are filtered out before `MongoSinkTask.bulkWriteBatch` is called.

2021-03-02 15:49 UTC, stIncMale approved these changes

2021-03-02 16:54 UTC, rozza commented
As  thanks for the review @stIncMale !

2021-03-02 16:54 UTC, closed without merging